#!/bin/bash
# S0_env_check.sh - PCIe 驱动开发环境验证（宿主机执行）
echo "=== S0 环境验证 ==="
echo "[1] QEMU 版本"
/opt/qemu/bin/qemu-system-x86_64 --version 2>/dev/null || echo "ERROR"
echo "[2] GCC 版本"
gcc --version 2>/dev/null | head -1 || echo "ERROR"
echo "[3] GDB Python 支持"
gdb -batch -ex "python print('GDB python OK')" 2>/dev/null && echo "OK" || echo "ERROR"
echo "[4] Linux headers"
ls /lib/modules/$(uname -r)/build 2>/dev/null >/dev/null && echo "OK" || echo "ERROR"
echo "[5] PCI 子系统配置"
grep -E "CONFIG_PCI=|CONFIG_PCI_MSI=|CONFIG_PCIEAER=" /boot/config-$(uname -r) 2>/dev/null | head -5 || echo "ERROR"
echo "[6] /dev/kvm 权限"
ls -l /dev/kvm 2>/dev/null || echo "ERROR"
echo "=== 验证完成 ==="
